name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-python@v3
        with:
          python-version: '>=3.9.0'
      - uses: tj-actions/changed-files@v19
        id: changed-files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: python -m pip install .
      - run: build-depot -o checks.json ${{ steps.changed-files.outputs.all_changed_files }}
        continue-on-error: true
      - uses: agyemanjp/ci-checks-action@v2.1.1
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          checks: |
            [{
              "name": "validate",
              "fileName": "checks.json",
              "prChangesOnly": true
            }]